//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Manager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Manager : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Manager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Manager"",
    ""maps"": [
        {
            ""name"": ""mana"",
            ""id"": ""8ac1df9b-2996-4a81-b4df-58bed7cc7cb2"",
            ""actions"": [
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""e4451f9e-9086-49f9-baa6-43f5afb8ff78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2edf9213-c206-4968-9372-fe58740bf7b6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // mana
        m_mana = asset.FindActionMap("mana", throwIfNotFound: true);
        m_mana_Space = m_mana.FindAction("Space", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // mana
    private readonly InputActionMap m_mana;
    private IManaActions m_ManaActionsCallbackInterface;
    private readonly InputAction m_mana_Space;
    public struct ManaActions
    {
        private @Manager m_Wrapper;
        public ManaActions(@Manager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Space => m_Wrapper.m_mana_Space;
        public InputActionMap Get() { return m_Wrapper.m_mana; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManaActions set) { return set.Get(); }
        public void SetCallbacks(IManaActions instance)
        {
            if (m_Wrapper.m_ManaActionsCallbackInterface != null)
            {
                @Space.started -= m_Wrapper.m_ManaActionsCallbackInterface.OnSpace;
                @Space.performed -= m_Wrapper.m_ManaActionsCallbackInterface.OnSpace;
                @Space.canceled -= m_Wrapper.m_ManaActionsCallbackInterface.OnSpace;
            }
            m_Wrapper.m_ManaActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
            }
        }
    }
    public ManaActions @mana => new ManaActions(this);
    public interface IManaActions
    {
        void OnSpace(InputAction.CallbackContext context);
    }
}
